version: '3.9'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: delivops
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      POSTGRES_DB: delivops
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "delivops"]
      interval: 10s
      timeout: 5s
      retries: 5
  api:
    build: ./backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    environment:
      - LOKI_URL=http://loki:3100/loki/api/v1/push
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
  web:
    build: ./frontend
    command: npm run dev
    volumes:
      - ./frontend:/app
    env_file:
      - ./frontend/.env.local
    environment:
      - PORT=3000
    ports:
      - "3000:3000"
    depends_on:
      - api
  loki:
    image: grafana/loki:2.9.1
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
  grafana:
    image: grafana/grafana:10.1.0
    ports:
      - "3001:3000"
    volumes:
      - ./observability/grafana/dashboards:/var/lib/grafana/dashboards
      - ./observability/grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - loki
volumes:
  db_data:
