version: '3.9'
services:
  api:
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    environment:
      - LOKI_URL=http://loki:3100/loki/api/v1/push
      - UVICORN_RELOAD=false
  web:
    command: ["sh", "-c", "npm run build && npm run start"]
    environment:
      - PORT=3000
      - API_PROXY_TARGET=http://api:8000
      - NODE_ENV=production
